version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: cloudy-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cloudy
      - MYSQL_DATABASE=cloudy1234!
    ports:
      - "3306:3306" # MySQL 기본 포트를 외부에 노출
    volumes:
      - db:/var/lib/mysql # MySQL 데이터를 영구적으로 저장
    networks:
      - cloudy
    restart: "always"

  cloudy-be:
    image: cloudy-be:latest
    container_name: cloudy-be
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    restart: "always"
    networks:
      - cloudy

  companyservice-be:
    image: companyservice-be:latest
    container_name: companyservice-be
    ports:
      - "8082:8082"
    restart: "always"
    networks:
      - cloudy
  externalservice-be:
    image: externalservice-be:latest
    container_name: externalservice-be
    ports:
      - "4041:4041"
    restart: "always"
    networks:
      - cloudy

  nginx-reverse:
    image: nginx:latest
    container_name: nginx-reverse
    ports:
      - "80:80"       # 리버스 프록시용 HTTP 포트
      - "443:443"     # 리버스 프록시용 HTTPS 포트
    volumes:
      - /etc/nginx/reverse:/etc/nginx  # 리버스 프록시 설정 파일 경로
      - /var/www/html:/var/www/html  # 정적 파일 제공을 위한 경로
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 경로
    depends_on:
      - cloudy-be
    restart: "always"
    networks:
      - cloudy

  nginx-forward:
    image: nginx:latest
    container_name: nginx-forward
    ports:
      - "8888:8888"  # 포워드 프록시용 포트 (클라이언트에서 포워드 프록시로 요청할 포트)
    volumes:
      - /etc/nginx/forward:/etc/nginx  # 포워드 프록시 설정 파일 경로
    restart: "always"
    networks:
      - cloudy

volumes:
  db: {}

networks:
  cloudy:
    name: cloudy
    driver: bridge
